/* Stable asset ids and id-aware merging (Devon, Sept 2026).

   Every array item gets an id generated by CODE at first write. Never
   positional, never derived from capture order, never reused after
   deletion (random UUIDs make reuse impossible). linked_asset_id and the
   reconciliation pass walk ids.

   Merge semantics: arrays of objects merge BY ID. A patch item carrying
   the id of an existing item updates that item in place; a patch item
   without an id (or with an unknown id) appends as a new item and gets
   its id at the write. Items the patch does not mention are retained —
   the capture protocol sends only what this turn provided, so a patch
   array is never a full replacement. (The old wholesale-replace merge
   silently dropped unmentioned items.)

   Migration: existing rows get ids on their first write after this lands
   (assignAssetIds over the base). Positional income links ("prop-N", from
   the short-lived capture-order convention) carry across only where the
   mapping is unambiguous — exactly one property and the link is prop-1.
   Anywhere else the link is cleared, never remapped by guess, and the
   reconciliation pass then surfaces the unlinked producer in
   flags.income_unreconciled. */

const ARRAY_ITEM_FIELDS = {
  context: ["children"],
  super: ["funds"],
  investments: ["properties"],
  debts: ["items"],
  income: ["other"],
};

function isObj(v) { return v && typeof v === "object" && !Array.isArray(v); }

export function newAssetId() {
  return crypto.randomUUID().slice(0, 8);
}

/* Give every object item in the known arrays an id if it lacks one.
   Returns a new domains object; never mutates the input. */
export function assignAssetIds(domains) {
  if (!isObj(domains)) return domains;
  const out = { ...domains };
  for (const [domainKey, fields] of Object.entries(ARRAY_ITEM_FIELDS)) {
    const dom = out[domainKey];
    if (!isObj(dom)) continue;
    let changed = false;
    const nd = { ...dom };
    for (const f of fields) {
      if (!Array.isArray(nd[f])) continue;
      nd[f] = nd[f].map(item => {
        if (!isObj(item)) return item;
        if (typeof item.id === "string" && item.id) return item;
        changed = true;
        return { id: newAssetId(), ...item };
      });
    }
    if (changed) out[domainKey] = nd;
  }
  return out;
}

/* deepMerge with id-aware array handling for the known item arrays.
   Scalar arrays (employer_super_on, flags.income_unreconciled) replace,
   as before. */
export function mergeDomainsById(base, patch) {
  function mergeVal(b, p, itemArray) {
    if (p === null || typeof p !== "object") return p;
    if (Array.isArray(p)) {
      if (!itemArray || !Array.isArray(b)) return p;
      const out = b.slice();
      for (const item of p) {
        if (!isObj(item)) { out.push(item); continue; }
        const ix = typeof item.id === "string" && item.id
          ? out.findIndex(x => isObj(x) && x.id === item.id) : -1;
        // { id, _remove: true } deletes the item; surviving items keep
        // their ids (never positional, never reused), and a _remove for
        // an unknown id is ignored rather than appended.
        if (item._remove === true) {
          if (ix !== -1) out.splice(ix, 1);
          continue;
        }
        if (ix === -1) out.push(item);
        else out[ix] = mergeVal(out[ix], item, false);
      }
      return out;
    }
    const out = { ...(isObj(b) ? b : {}) };
    for (const [k, v] of Object.entries(p)) out[k] = mergeVal(out[k], v, false);
    return out;
  }

  if (!isObj(patch)) return patch;
  const out = { ...(isObj(base) ? base : {}) };
  for (const [domainKey, domVal] of Object.entries(patch)) {
    if (!isObj(domVal)) { out[domainKey] = domVal; continue; }
    const baseDom = isObj(out[domainKey]) ? out[domainKey] : {};
    const nd = { ...baseDom };
    const itemFields = ARRAY_ITEM_FIELDS[domainKey] || [];
    for (const [k, v] of Object.entries(domVal)) {
      nd[k] = mergeVal(nd[k], v, itemFields.includes(k));
    }
    out[domainKey] = nd;
  }
  return out;
}

/* Positional link migration. Runs AFTER assignAssetIds, so properties
   carry real ids. prop-1 with exactly one property is the only
   unambiguous mapping; everything else clears to null (never a guessed
   remap) and the reconciliation pass surfaces the open producer. */
export function migratePositionalLinks(domains) {
  if (!isObj(domains)) return domains;
  const inc = domains.income;
  if (!isObj(inc) || !Array.isArray(inc.other)) return domains;
  const props = isObj(domains.investments) && Array.isArray(domains.investments.properties)
    ? domains.investments.properties : [];
  let changed = false;
  const other = inc.other.map(o => {
    if (!isObj(o) || typeof o.linked_asset_id !== "string") return o;
    const m = o.linked_asset_id.match(/^prop-(\d+)$/);
    if (!m) return o;
    changed = true;
    if (m[1] === "1" && props.length === 1 && isObj(props[0]) && props[0].id) {
      return { ...o, linked_asset_id: props[0].id };
    }
    return { ...o, linked_asset_id: null };
  });
  if (!changed) return domains;
  return { ...domains, income: { ...inc, other } };
}

/* Security auto-resolution (Devon item 4, Sept 2026): credit_card, bnpl,
   hecs_help and tax_debt cannot carry security — code resolves it to
   unsecured without any trip. Deterministic fact, not a guess. */
const UNSECURABLE_TYPES = ["credit_card", "bnpl", "hecs_help", "tax_debt"];
export function resolveSecurity(domains) {
  if (!isObj(domains)) return domains;
  const debts = domains.debts;
  if (!isObj(debts) || !Array.isArray(debts.items)) return domains;
  let changed = false;
  const items = debts.items.map(it => {
    if (!isObj(it)) return it;
    if (UNSECURABLE_TYPES.includes(it.type) && (it.security === null || it.security === undefined)) {
      changed = true;
      return { ...it, security: "unsecured" };
    }
    return it;
  });
  if (!changed) return domains;
  return { ...domains, debts: { ...debts, items } };
}
