/* Stable asset ids and id-aware merging (Devon, Sept 2026).

   Every array item gets an id generated by CODE at first write. Never
   positional, never derived from capture order, never reused after
   deletion (random UUIDs make reuse impossible). linked_asset_id and the
   reconciliation pass walk ids.

   Merge semantics: arrays of objects merge BY ID. A patch item carrying
   the id of an existing item updates that item in place; a patch item
   without an id (or with an unknown id) appends as a new item and gets
   its id at the write. Items the patch does not mention are retained —
   the capture protocol sends only what this turn provided, so a patch
   array is never a full replacement. (The old wholesale-replace merge
   silently dropped unmentioned items.)

   Migration: existing rows get ids on their first write after this lands
   (assignAssetIds over the base). Positional income links ("prop-N", from
   the short-lived capture-order convention) carry across only where the
   mapping is unambiguous — exactly one property and the link is prop-1.
   Anywhere else the link is cleared, never remapped by guess, and the
   reconciliation pass then surfaces the unlinked producer in
   flags.income_unreconciled. */

const ARRAY_ITEM_FIELDS = {
  context: ["children"],
  super: ["funds"],
  investments: ["properties"],
  debts: ["items"],
  income: ["other"],
};

function isObj(v) { return v && typeof v === "object" && !Array.isArray(v); }

export function newAssetId() {
  return crypto.randomUUID().slice(0, 8);
}

/* Give every object item in the known arrays an id if it lacks one.
   Returns a new domains object; never mutates the input. */
export function assignAssetIds(domains) {
  if (!isObj(domains)) return domains;
  const out = { ...domains };
  for (const [domainKey, fields] of Object.entries(ARRAY_ITEM_FIELDS)) {
    const dom = out[domainKey];
    if (!isObj(dom)) continue;
    let changed = false;
    const nd = { ...dom };
    for (const f of fields) {
      if (!Array.isArray(nd[f])) continue;
      nd[f] = nd[f].map(item => {
        if (!isObj(item)) return item;
        if (typeof item.id === "string" && item.id) return item;
        changed = true;
        return { id: newAssetId(), ...item };
      });
    }
    if (changed) out[domainKey] = nd;
  }
  return out;
}

/* deepMerge with id-aware array handling for the known item arrays.
   Scalar arrays (employer_super_on, flags.income_unreconciled) replace,
   as before. */
export function mergeDomainsById(base, patch) {
  function mergeVal(b, p, itemArray) {
    if (p === null || typeof p !== "object") return p;
    if (Array.isArray(p)) {
      if (!itemArray || !Array.isArray(b)) return p;
      const out = b.slice();
      for (const item of p) {
        if (!isObj(item)) { out.push(item); continue; }
        const ix = typeof item.id === "string" && item.id
          ? out.findIndex(x => isObj(x) && x.id === item.id) : -1;
        // { id, _remove: true } deletes the item; surviving items keep
        // their ids (never positional, never reused), and a _remove for
        // an unknown id is ignored rather than appended.
        if (item._remove === true) {
          if (ix !== -1) out.splice(ix, 1);
          continue;
        }
        if (ix === -1) out.push(item);
        else out[ix] = mergeVal(out[ix], item, false);
      }
      return out;
    }
    const out = { ...(isObj(b) ? b : {}) };
    for (const [k, v] of Object.entries(p)) out[k] = mergeVal(out[k], v, false);
    return out;
  }

  if (!isObj(patch)) return patch;
  const out = { ...(isObj(base) ? base : {}) };
  for (const [domainKey, domVal] of Object.entries(patch)) {
    if (!isObj(domVal)) { out[domainKey] = domVal; continue; }
    const baseDom = isObj(out[domainKey]) ? out[domainKey] : {};
    const nd = { ...baseDom };
    const itemFields = ARRAY_ITEM_FIELDS[domainKey] || [];
    for (const [k, v] of Object.entries(domVal)) {
      nd[k] = mergeVal(nd[k], v, itemFields.includes(k));
    }
    out[domainKey] = nd;
  }
  return out;
}

/* Positional link migration. Runs AFTER assignAssetIds, so properties
   carry real ids. prop-1 with exactly one property is the only
   unambiguous mapping; everything else clears to null (never a guessed
   remap) and the reconciliation pass surfaces the open producer. */
export function migratePositionalLinks(domains) {
  if (!isObj(domains)) return domains;
  const inc = domains.income;
  if (!isObj(inc) || !Array.isArray(inc.other)) return domains;
  const props = isObj(domains.investments) && Array.isArray(domains.investments.properties)
    ? domains.investments.properties : [];
  let changed = false;
  const other = inc.other.map(o => {
    if (!isObj(o) || typeof o.linked_asset_id !== "string") return o;
    const m = o.linked_asset_id.match(/^prop-(\d+)$/);
    if (!m) return o;
    changed = true;
    if (m[1] === "1" && props.length === 1 && isObj(props[0]) && props[0].id) {
      return { ...o, linked_asset_id: props[0].id };
    }
    return { ...o, linked_asset_id: null };
  });
  if (!changed) return domains;
  return { ...domains, income: { ...inc, other } };
}

/* Security auto-resolution (Devon item 4, Sept 2026): credit_card, bnpl,
   hecs_help and tax_debt cannot carry security — code resolves it to
   unsecured without any trip. Deterministic fact, not a guess. */
const UNSECURABLE_TYPES = ["credit_card", "bnpl", "hecs_help", "tax_debt"];
export function resolveSecurity(domains) {
  if (!isObj(domains)) return domains;
  const debts = domains.debts;
  if (!isObj(debts) || !Array.isArray(debts.items)) return domains;
  let changed = false;
  const items = debts.items.map(it => {
    if (!isObj(it)) return it;
    if (UNSECURABLE_TYPES.includes(it.type) && (it.security === null || it.security === undefined)) {
      changed = true;
      return { ...it, security: "unsecured" };
    }
    return it;
  });
  if (!changed) return domains;
  return { ...domains, debts: { ...debts, items } };
}

/* Natural-key adoption (15 Sept walk): the model sometimes re-sends an
   existing item WITHOUT its id (a fund repeated to add has_insurance, a
   loan repeated to add its rate). Appending those duplicates the item. An
   id-less patch item that matches EXACTLY ONE existing item on its natural
   key adopts that item's id, so it updates in place. No match, or more
   than one, and it appends as before: ambiguity never guesses. */
function normName(s) {
  return String(s || "").toLowerCase().replace(/\bsuper(annuation)?\b/g, "").replace(/[^a-z0-9]/g, "");
}
// "unknown" is a placeholder, never a distinguishing value; dividends and
// distributions are the same family for matching.
const same = (a, b) => !a || !b || a === b || a === "unknown" || b === "unknown";
const sourceFamily = v => (v === "dividends" || v === "distributions") ? "div" : v;
const NATURAL_KEYS = {
  "super.funds": (b, p) => {
    const named = v => v && String(v).toLowerCase() !== "unknown";
    const sameOwner = !p.owner || !b.owner || String(b.owner).toLowerCase() === String(p.owner).toLowerCase();
    if (named(p.fund) && named(b.fund)) return normName(b.fund) === normName(p.fund) && sameOwner;
    // A fund with no name yet (walk 8: "Jess just has the one" stored a
    // nameless stub, then a second one as "unknown") matches on its owner.
    return !!(p.owner && b.owner) && sameOwner;
  },
  "debts.items": (b, p) => p.type && b.type === p.type
    && same(b.borrower, p.borrower) && same(b.purpose, p.purpose),
  "investments.properties": (b, p) => (p.held_in && b.held_in && String(b.held_in).toLowerCase() === String(p.held_in).toLowerCase()
    && (!p.use || !b.use || b.use === p.use))
    || (typeof p.value_estimate === "number" && b.value_estimate === p.value_estimate),
  "income.other": (b, p) => p.source && sourceFamily(b.source) === sourceFamily(p.source)
    && (!p.linked_asset_id || !b.linked_asset_id || b.linked_asset_id === p.linked_asset_id)
    && same(b.entity, p.entity),
  "context.children": (b, p) => typeof p.age === "number" && b.age === p.age,
};
// A second, looser pass for debts: the recorder and the model can disagree
// on whether a household loan is "personal" or "joint" (stand-in run 5
// stored the ETF split twice). Household-level holders are compatible; an
// entity holder never is.
const HOUSEHOLD_HOLDERS = new Set(["personal", "joint", "you", "partner", "unknown"]);
const hh = v => v === undefined || v === null || HOUSEHOLD_HOLDERS.has(String(v).toLowerCase());
const RELAXED_KEYS = {
  "debts.items": (b, p) => p.type && b.type === p.type && hh(b.borrower) && hh(p.borrower)
    && same(b.purpose, p.purpose)
    && (!p.parent_loan_id || !b.parent_loan_id || b.parent_loan_id === p.parent_loan_id),
};
export function adoptNaturalIds(base, patch) {
  if (!isObj(patch) || !isObj(base)) return patch;
  const out = { ...patch };
  for (const [domainKey, fields] of Object.entries(ARRAY_ITEM_FIELDS)) {
    const pd = out[domainKey], bd = base[domainKey];
    if (!isObj(pd) || !isObj(bd)) continue;
    let nd = null;
    for (const f of fields) {
      const match = NATURAL_KEYS[domainKey + "." + f];
      if (!match || !Array.isArray(pd[f]) || !Array.isArray(bd[f])) continue;
      const taken = new Set(pd[f].filter(i => isObj(i) && typeof i.id === "string").map(i => i.id));
      // Children (stand-in run 6: "2 kids" then their ages made six): a
      // child mentioned again lands on an existing child, never a new one,
      // while there are untaken children: same age first, then one with no
      // age yet, then (for a child mentioned without an age) any.
      if (domainKey === "context" && f === "children") {
        nd = nd || { ...pd };
        nd[f] = pd[f].map(item => {
          if (!isObj(item) || (typeof item.id === "string" && item.id) || item._remove) return item;
          const free = bd[f].filter(b => isObj(b) && b.id && !taken.has(b.id));
          const hasAge = typeof item.age === "number";
          const hit = (hasAge ? free.find(b => b.age === item.age) : null)
            || free.find(b => typeof b.age !== "number")
            || (!hasAge ? free[0] : null);
          if (!hit) return item;
          taken.add(hit.id);
          return { ...item, id: hit.id };
        });
        continue;
      }
      const known = new Set(bd[f].filter(b => isObj(b) && b.id).map(b => b.id));
      const arr = pd[f].map(item => {
        if (!isObj(item) || item._remove) return item;
        // An id the picture has never held is one the model made up (walk
        // 8: the split arrived as "442c90bf" and sat beside the split
        // already stored). It matches on the natural key like no id at all.
        if (typeof item.id === "string" && item.id && known.has(item.id)) return item;
        let hits = bd[f].filter(b => isObj(b) && b.id && !taken.has(b.id) && match(b, item));
        const relaxed = RELAXED_KEYS[domainKey + "." + f];
        if (hits.length === 0 && relaxed) hits = bd[f].filter(b => isObj(b) && b.id && !taken.has(b.id) && relaxed(b, item));
        if (hits.length > 1) {
          // Several candidates: the one agreeing on the most stated values
          // wins; a tie never guesses.
          const score = b => Object.keys(item).filter(k => !k.startsWith("_") && k !== "id" && item[k] !== null && item[k] !== undefined && b[k] === item[k]).length;
          const scored = hits.map(b => [b, score(b)]).sort((x, y) => y[1] - x[1]);
          hits = scored[0][1] > scored[1][1] ? [scored[0][0]] : hits;
        }
        if (hits.length !== 1) return item;
        taken.add(hits[0].id);
        return { ...item, id: hits[0].id };
      });
      nd = nd || { ...pd };
      nd[f] = arr;
    }
    if (nd) out[domainKey] = nd;
  }
  return out;
}
